version: '3.8'

# V6 Smart Parking - Production Deployment
# Uses shared infrastructure from parking-infrastructure stack
# Only deploys V6-specific application services

networks:
  parking-network:
    external: true  # Connect to shared infrastructure network

services:
  # API Service - V6
  api-v6:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: parking-v6-api:latest
    container_name: parking-api-v6
    restart: unless-stopped
    environment:
      # Use SHARED Postgres from infrastructure stack
      DATABASE_URL: postgresql://${DB_USER:-parking_user}:${DB_PASSWORD:-parking}@${DB_HOST:-parking-postgres}:5432/${DB_NAME:-parking_v6}
      # Use SHARED Redis from infrastructure stack (DB 1 for V6)
      REDIS_URL: redis://${REDIS_HOST:-parking-redis}:6379/${REDIS_DB:-1}
      # Use SHARED ChirpStack from infrastructure stack
      CHIRPSTACK_HOST: parking-chirpstack:8080
      CHIRPSTACK_API_KEY: ${CHIRPSTACK_API_KEY:-}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-your-secret-key-change-in-production}
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      ENVIRONMENT: production
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
      - /var/spool/parking-uplinks:/var/spool/parking-uplinks
    networks:
      - parking-network
    labels:
      - "traefik.enable=true"
      # Production API route (supports both api.verdegris.eu and api-v6.verdegris.eu for backwards compatibility)
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.rule=Host(`api.verdegris.eu`) || Host(`api-v6.verdegris.eu`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.middlewares=api-v6-cors"
      - "traefik.http.services.api-v6.loadbalancer.server.port=8000"
      # CORS headers
      - "traefik.http.middlewares.api-v6-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS,PATCH"
      - "traefik.http.middlewares.api-v6-cors.headers.accesscontrolallowheaders=Content-Type,Authorization,Accept,Origin,X-Requested-With"
      - "traefik.http.middlewares.api-v6-cors.headers.accesscontrolalloworiginlist=https://parking.eroundit.eu,https://app.parking.verdegris.eu,https://parking.verdegris.eu"
      - "traefik.http.middlewares.api-v6-cors.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.api-v6-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.api-v6-cors.headers.addvaryheader=true"
      - "traefik.http.routers.api-v6.middlewares=api-v6-cors"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend - V6
  frontend-v6:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-https://api.verdegris.eu}
        VITE_WS_URL: ${VITE_WS_URL:-wss://api.verdegris.eu/ws}
    image: parking-v6-frontend:latest
    container_name: parking-frontend-v6
    restart: unless-stopped
    networks:
      - parking-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.parking.verdegris.eu`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database Admin - Adminer V6
  adminer-v6:
    image: adminer:latest
    container_name: parking-adminer-v6
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: parking-postgres  # Points to infrastructure Postgres
      ADMINER_DESIGN: nette
    networks:
      - parking-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer-v6.entrypoints=websecure"
      - "traefik.http.routers.adminer-v6.rule=Host(`db-v6.verdegris.eu`)"
      - "traefik.http.routers.adminer-v6.tls=true"
      - "traefik.http.routers.adminer-v6.tls.certresolver=letsencrypt"
      - "traefik.http.services.adminer-v6.loadbalancer.server.port=8080"
