version: '3.8'

networks:
  parking-network:
    name: parking-v5_parking-network
    external: true

volumes:
  # New V6 volumes
  v6_uploads:
    driver: local
  v6_spool:
    driver: local
  v6_logs:
    driver: local

services:
  # ============================================
  # V6 API Service (Replaces parking-v5-api)
  # ============================================
  api-v6:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: parking-api-v6
    restart: unless-stopped
    networks:
      - parking-network
    environment:
      # Database (shared with V5)
      DATABASE_URL: postgresql://parking_user:${DB_PASSWORD}@parking-postgres:5432/parking_v6

      # Redis (shared with V5)
      REDIS_URL: redis://parking-redis:6379/1

      # ChirpStack (shared)
      CHIRPSTACK_HOST: parking-chirpstack
      CHIRPSTACK_PORT: 8080
      CHIRPSTACK_API_KEY: ${CHIRPSTACK_API_KEY}

      # Application
      SECRET_KEY: ${SECRET_KEY}
      LOG_LEVEL: INFO
      CORS_ORIGINS: https://api.verdegris.eu,https://app.verdegris.eu,https://api-v6.verdegris.eu,http://localhost:3000

      # V6 Specific
      ENABLE_RLS: "true"
      USE_V6_API: "true"
      PLATFORM_TENANT_ID: 00000000-0000-0000-0000-000000000000

      # Webhook
      WEBHOOK_SECRET_KEY: ${WEBHOOK_SECRET_KEY}
      WEBHOOK_SPOOL_DIR: /var/spool/parking-uplinks

      # JWT
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 7
    volumes:
      - v6_uploads:/app/uploads
      - v6_spool:/var/spool/parking-uplinks
      - v6_logs:/app/logs
    labels:
      # Traefik routing for V6 API
      - "traefik.enable=true"
      - "traefik.http.routers.api-v6.rule=Host(`api-v6.verdegris.eu`) || (Host(`api.verdegris.eu`) && PathPrefix(`/api/v6`))"
      - "traefik.http.routers.api-v6.tls=true"
      - "traefik.http.routers.api-v6.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api-v6.priority=50"
      - "traefik.http.services.api-v6.loadbalancer.server.port=8000"
      # CORS headers
      - "traefik.http.middlewares.api-v6-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS,PATCH"
      - "traefik.http.middlewares.api-v6-cors.headers.accesscontrolalloworiginlist=https://api.verdegris.eu,https://app.verdegris.eu,https://api-v6.verdegris.eu"
      - "traefik.http.middlewares.api-v6-cors.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.api-v6-cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.routers.api-v6.middlewares=api-v6-cors"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ============================================
  # Supporting Services (Use V6 versions)
  # ============================================

  # Admin Database UI
  adminer-v6:
    image: adminer:latest
    container_name: parking-adminer-v6
    restart: unless-stopped
    networks:
      - parking-network
    environment:
      ADMINER_DEFAULT_SERVER: parking-postgres
      ADMINER_DESIGN: pepa-linha
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer-v6.rule=Host(`adminer-v6.verdegris.eu`)"
      - "traefik.http.routers.adminer-v6.tls=true"
      - "traefik.http.routers.adminer-v6.tls.certresolver=letsencrypt"
      - "traefik.http.routers.adminer-v6.priority=50"
      - "traefik.http.routers.adminer-v6.middlewares=adminer-auth"
      - "traefik.http.middlewares.adminer-auth.basicauth.users=${ADMIN_CREDENTIALS}"
      - "traefik.http.services.adminer-v6.loadbalancer.server.port=8080"

  # File Browser
  filebrowser-v6:
    image: filebrowser/filebrowser:latest
    container_name: parking-filebrowser-v6
    restart: unless-stopped
    networks:
      - parking-network
    volumes:
      - v6_uploads:/srv/uploads
      - v6_logs:/srv/logs
      - v6_spool:/srv/spool
      - ./config/filebrowser:/config
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.files-v6.rule=Host(`files-v6.verdegris.eu`)"
      - "traefik.http.routers.files-v6.tls=true"
      - "traefik.http.routers.files-v6.tls.certresolver=letsencrypt"
      - "traefik.http.routers.files-v6.priority=50"
      - "traefik.http.routers.files-v6.middlewares=files-auth"
      - "traefik.http.middlewares.files-auth.basicauth.users=${ADMIN_CREDENTIALS}"
      - "traefik.http.services.files-v6.loadbalancer.server.port=80"
